# Generated by Django 5.0.1 on 2024-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=36)),
                ('id_plano', models.IntegerField(null=True)),
                ('id_design', models.IntegerField(null=True)),
                ('nome_1', models.CharField(max_length=100)),
                ('nome_2', models.CharField(max_length=100)),
                ('data', models.DateField(null=True)),
                ('convidados', models.IntegerField(default=50)),
                ('decoracao', models.CharField(max_length=15)),
                ('buffet', models.CharField(max_length=15)),
                ('items_cerimonia', models.CharField(max_length=15)),
                ('flores', models.CharField(max_length=15)),
                ('transporte', models.CharField(max_length=15)),
            ],
        ),
    ]
